# Generated by Django 3.2.18 on 2023-05-11 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('inquiry_name', models.CharField(max_length=75)),
                ('inquiry_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='Enter a 10-digit phone number.', max_length=10, validators=[django.core.validators.RegexValidator('^\\+\\d{2}\\s\\d{10}$')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('inquiry_message', models.TextField()),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
