# Generated by Django 3.2.18 on 2023-05-11 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(help_text='+XX XXXXXXXXXX', max_length=14, validators=[django.core.validators.RegexValidator('^\\+\\d{2}\\s\\d{10}$')]),
        ),
    ]
