# Generated by Django 3.2.18 on 2023-05-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactus_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_date']},
        ),
    ]
