# Generated by Django 3.2.18 on 2023-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=200)),
                ('player_numbers', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time_slot', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
