# Generated by Django 3.2.18 on 2023-05-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_reservation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('room_description', models.TextField()),
            ],
            options={
                'ordering': ['room_name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_choice', to='bookings.room'),
        ),
    ]
