# Generated by Django 3.2.18 on 2023-05-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20230503_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_choice', to='bookings.room'),
        ),
    ]
