# Generated by Django 3.2.18 on 2023-05-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_reservation_room_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_choice',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
