# Generated by Django 3.2.18 on 2023-05-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20230504_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slot', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['game_slot'],
            },
        ),
    ]
