# Generated by Django 3.2.18 on 2023-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_gametime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(default='', max_length=300),
        ),
    ]
