# Generated by Django 3.2.18 on 2023-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_reservation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
