# Generated by Django 3.2.18 on 2023-05-12 09:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_reservation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='blog_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
