# Generated by Django 3.2.18 on 2023-05-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_room_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametime',
            name='game_slot',
            field=models.CharField(choices=[('00:00', '00:00'), ('02:00', '02:00'), ('04:00', '04:00'), ('06:00', '06:00'), ('08:00', '08:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('16:00', '16:00'), ('18:00', '18:00'), ('20:00', '20:00'), ('22:00', '22:00')], max_length=5),
        ),
    ]
